### ISSUE TITLE
Clean up wiki text

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc-documentation#2]
List of tasks

* [ ] All literal references (values, term names, button labels in software) should be in `code`
* [ ] All examples in code blocks using 3 backticks
* [ ] Remove references to old wiki
* [ ] Make sure there are no `!CamelCase` names
* [ ] CV values should be in code blocks

## Terms.md

* [ ] Remove reference to [GeologicalContext](https://code.google.com/p/darwincore/wiki/GeologicalContext) in terms.md
* [ ] Remove reference to [Type Vocabulary Terms](DwCTypeVocabulary)
* [ ] Update references to semicolon
* [ ] Update references to dwctype

You're welcome to add more.

**Comment by tucotuco** [comment]
All moved to dwc repository.
