### ISSUE TITLE
Beautiful documentation generator

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc-documentation#3]
Not entirely sure this is specific to this repository only, but I'm looking at tools that can generate beautiful documentation from the markdown files. GitHub is doing a good job already, but it would be nice if we can host something even more accessible on `gh-pages`.

Here's a good list of tools: https://github.com/PharkMillups/beautiful-docs#generating-docs

One of those tools might also tie into our idea of generating everything from the normative document.

**Comment by tucotuco** [comment]
Working only in dwc repository now.

**Comment by peterdesmet** [comment]
I'll move this information into a new issue at dwc, so we don't lose it if we delete this repo.
