### ISSUE TITLE
Darwin Core guidelines repository

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc-documentation#5]
*Note: this is something we discussed at the TDWG 2014 meeting in Sweden*:

The Darwin Core term definitions and comments are not enough for most users to know how to best standardize their data for publication. What they need are **use case guidelines for Darwin Core**, e.g. how to use DwC for herbaria, tracking data, taxonomic checklists, etc. Some of these guidelines already exist (with different levels of completeness and many potential ones listed [here](https://github.com/tdwg/dwc-documentation/blob/master/documentation/examples.md)). These guidelines discuss which terms are relevant for a certain use case (and which are not), how to populate the terms (while still following the definitions), and typically tackle combinations of terms (not just atomic terms).

I'd like to start a discussion how we bring those guidelines together in a collaborative, open environment. Here are my thoughts:

1. Guidelines should be single document, which makes it easier for searching.
2. Guidelines should be published under an open license (cc0 or cc by).
3. Guidelines should make copious use of examples (in code blocks)
4. Contributing to guidelines should be easy.
5. Guidelines should have version control and be reference-able (would allow anyone to specify which version they used).
6. Guidelines could be written as specs (with `MUST`, `MAY`, etc.), but this makes it a bit harder to contribute.
7. References can be made within guidelines using anchors.
8. Guidelines can rely on other guidelines for some sections (e.g. reference the main DwC guidelines/wiki for the `georeference` terms). Not sure if these sections should referenced or incorporated (version question).
9. It should be possible to start new guidelines based on existing ones.
10. ...

I am of course seeing this through GitHub, where guidelines are single Markdown documents (maybe directories if we want to account for images). Suggestions can be made using pull requests, it's versioned, open, we have issues, etc. I don't know yet if I'd prefer a single repository for all guidelines (e.g. this repository, renamed to `dwc-guidelines`) or if this would work better as one repository per use case guideline.

What are your thoughts?

/cc @cgendreau

**Comment by tucotuco** [comment]
Merging all into dwc repository.
